### ISSUE TITLE
Could someone help me?

### ISSUE THREAD

**Issue by iliveinpain** [qilingframework/qiling#1057]
![image](https://user-images.githubusercontent.com/56503656/147905163-b15bd971-54d3-4f35-a01c-e2413f1883ae.png)

**Comment by elicn** [comment]
Hi there and welcome.
It looks like you are running `qltool` from outside of the qiling directory; since `qltool` is probably in `$PATH` it executes fine, but the path to the rootfs directory breaks. Try `cd` back to the qiling directory and run it again [son't forget to adjust the path to `sample.exe` accordingly].

Here are a few tips:
- When specifying a path or filename in Linux command line, use the autocompletion feature (i.e. use the `tab` key). If a prefix doesn't complete, the path is probably broken or doesn't lead to where you thought it would
- If you want to browse or search through `qltool` output, you can pipe it to `less` like this:
```bash
./qltool run --rootfs/x86_windows -f ../sample.exe 2>&1 | less
```
- and the final tip would be joining our Telegram channel, which would be a more suitable place for troubleshooting and beginners questions: https://t.me/qilingframework

**Comment by xwings** [comment]
rootfs is in here.

https://github.com/qilingframework/rootfs

But, this is a windows exe. Meaning all the required exe needs to obtained manually. Checkout the script folder and the bat file

**Comment by xwings** [comment]
Issue is in faq. Issue closed.
