### ISSUE TITLE
Hello, I am writing this because the library could not be processed on the MacBook m1.

### ISSUE THREAD

**Issue by f10w3r-s** [qilingframework/qiling#1093]
## intro
Hello, I am writing this because the library could not be processed on the MacBook m1.

```pip3 install qiling```

## Error message
```
Collecting qiling
  Using cached qiling-1.4.2-py3-none-any.whl (922 kB)
Requirement already satisfied: pefile>=2021.9.3 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (2021.9.3)
Requirement already satisfied: python-registry>=1.3.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (1.3.1)
Requirement already satisfied: capstone>=4.0.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (4.0.2)
Requirement already satisfied: gevent>=20.9.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (21.12.0)
Requirement already satisfied: pyyaml>=6.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (6.0)
Collecting unicorn>=2.0.0-rc5
  Using cached unicorn-2.0.0rc6.tar.gz (2.6 MB)
Requirement already satisfied: pyelftools>=0.26 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (0.28)
Collecting keystone-engine>=0.9.2
  Using cached keystone-engine-0.9.2.tar.gz (2.8 MB)
Requirement already satisfied: multiprocess>=0.70.12.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (0.70.12.2)
Requirement already satisfied: future in /home/ubuntu/.local/lib/python3.8/site-packages (from pefile>=2021.9.3->qiling) (0.18.2)
Requirement already satisfied: enum-compat in /home/ubuntu/.local/lib/python3.8/site-packages (from python-registry>=1.3.1->qiling) (0.0.3)
Requirement already satisfied: unicodecsv in /home/ubuntu/.local/lib/python3.8/site-packages (from python-registry>=1.3.1->qiling) (0.14.1)
Requirement already satisfied: zope.interface in /usr/lib/python3/dist-packages (from gevent>=20.9.0->qiling) (4.7.1)
Requirement already satisfied: greenlet<2.0,>=1.1.0; platform_python_implementation == "CPython" in /home/ubuntu/.local/lib/python3.8/site-packages (from gevent>=20.9.0->qiling) (1.1.2)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from gevent>=20.9.0->qiling) (45.2.0)
Requirement already satisfied: zope.event in /home/ubuntu/.local/lib/python3.8/site-packages (from gevent>=20.9.0->qiling) (4.5.0)
Requirement already satisfied: dill>=0.3.4 in /home/ubuntu/.local/lib/python3.8/site-packages (from multiprocess>=0.70.12.2->qiling) (0.3.4)
Building wheels for collected packages: unicorn, keystone-engine
  Building wheel for unicorn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fs9zu9a_/unicorn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fs9zu9a_/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-e1ep09n4
       cwd: /tmp/pip-install-fs9zu9a_/unicorn/
  Complete output (4 lines):
  running bdist_wheel
  running build
  Building C extensions
  error: [Errno 2] No such file or directory: '/tmp/pip-install-fs9zu9a_/unicorn/../../include/unicorn'
  ----------------------------------------
  ERROR: Failed building wheel for unicorn
  Running setup.py clean for unicorn
  Building wheel for keystone-engine (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fs9zu9a_/keystone-engine/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fs9zu9a_/keystone-engine/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-e0m3wvzh
       cwd: /tmp/pip-install-fs9zu9a_/keystone-engine/
  Complete output (6 lines):
  running bdist_wheel
  running build
  Building C++ extensions
  ../make-share.sh: 21: cmake: not found
  make: *** No targets specified and no makefile found.  Stop.
  error: [Errno 2] No such file or directory: '/tmp/pip-install-fs9zu9a_/keystone-engine/src/build/llvm/lib64/libkeystone.so'
  ----------------------------------------
  ERROR: Failed building wheel for keystone-engine
  Running setup.py clean for keystone-engine
Failed to build unicorn keystone-engine
Installing collected packages: unicorn, keystone-engine, qiling
  Attempting uninstall: unicorn
    Found existing installation: unicorn 1.0.3
    Uninstalling unicorn-1.0.3:
      Successfully uninstalled unicorn-1.0.3
    Running setup.py install for unicorn ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fs9zu9a_/unicorn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fs9zu9a_/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dq2s5nff/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ubuntu/.local/include/python3.8/unicorn
         cwd: /tmp/pip-install-fs9zu9a_/unicorn/
    Complete output (4 lines):
    running install
    running build
    Building C extensions
    error: [Errno 2] No such file or directory: '/tmp/pip-install-fs9zu9a_/unicorn/../../include/unicorn'
    ----------------------------------------
  Rolling back uninstall of unicorn
  Moving to /home/ubuntu/.local/lib/python3.8/site-packages/unicorn-1.0.3.dist-info/
   from /home/ubuntu/.local/lib/python3.8/site-packages/~nicorn-1.0.3.dist-info
  Moving to /home/ubuntu/.local/lib/python3.8/site-packages/unicorn/
   from /home/ubuntu/.local/lib/python3.8/site-packages/~nicorn
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fs9zu9a_/unicorn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fs9zu9a_/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dq2s5nff/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ubuntu/.local/include/python3.8/unicorn Check the logs for full command output.
```

**Comment by wtdcode** [comment]
Unicorn doesn’t have a precompiled package for M1 laptop so you have to install it by your own.
________________________________
From: f10w3r-s ***@***.***>
Sent: Wednesday, February 16, 2022 8:24:03 AM
To: qilingframework/qiling ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [qilingframework/qiling] Hello, I am writing this because the library could not be processed on the MacBook m1. (Issue #1093)


intro

Hello, I am writing this because the library could not be processed on the MacBook m1.

pip3 install qiling

Error message

Collecting qiling
  Using cached qiling-1.4.2-py3-none-any.whl (922 kB)
Requirement already satisfied: pefile>=2021.9.3 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (2021.9.3)
Requirement already satisfied: python-registry>=1.3.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (1.3.1)
Requirement already satisfied: capstone>=4.0.1 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (4.0.2)
Requirement already satisfied: gevent>=20.9.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (21.12.0)
Requirement already satisfied: pyyaml>=6.0 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (6.0)
Collecting unicorn>=2.0.0-rc5
  Using cached unicorn-2.0.0rc6.tar.gz (2.6 MB)
Requirement already satisfied: pyelftools>=0.26 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (0.28)
Collecting keystone-engine>=0.9.2
  Using cached keystone-engine-0.9.2.tar.gz (2.8 MB)
Requirement already satisfied: multiprocess>=0.70.12.2 in /home/ubuntu/.local/lib/python3.8/site-packages (from qiling) (0.70.12.2)
Requirement already satisfied: future in /home/ubuntu/.local/lib/python3.8/site-packages (from pefile>=2021.9.3->qiling) (0.18.2)
Requirement already satisfied: enum-compat in /home/ubuntu/.local/lib/python3.8/site-packages (from python-registry>=1.3.1->qiling) (0.0.3)
Requirement already satisfied: unicodecsv in /home/ubuntu/.local/lib/python3.8/site-packages (from python-registry>=1.3.1->qiling) (0.14.1)
Requirement already satisfied: zope.interface in /usr/lib/python3/dist-packages (from gevent>=20.9.0->qiling) (4.7.1)
Requirement already satisfied: greenlet<2.0,>=1.1.0; platform_python_implementation == "CPython" in /home/ubuntu/.local/lib/python3.8/site-packages (from gevent>=20.9.0->qiling) (1.1.2)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from gevent>=20.9.0->qiling) (45.2.0)
Requirement already satisfied: zope.event in /home/ubuntu/.local/lib/python3.8/site-packages (from gevent>=20.9.0->qiling) (4.5.0)
Requirement already satisfied: dill>=0.3.4 in /home/ubuntu/.local/lib/python3.8/site-packages (from multiprocess>=0.70.12.2->qiling) (0.3.4)
Building wheels for collected packages: unicorn, keystone-engine
  Building wheel for unicorn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fs9zu9a_/unicorn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fs9zu9a_/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-e1ep09n4
       cwd: /tmp/pip-install-fs9zu9a_/unicorn/
  Complete output (4 lines):
  running bdist_wheel
  running build
  Building C extensions
  error: [Errno 2] No such file or directory: '/tmp/pip-install-fs9zu9a_/unicorn/../../include/unicorn'
  ----------------------------------------
  ERROR: Failed building wheel for unicorn
  Running setup.py clean for unicorn
  Building wheel for keystone-engine (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fs9zu9a_/keystone-engine/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fs9zu9a_/keystone-engine/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-e0m3wvzh
       cwd: /tmp/pip-install-fs9zu9a_/keystone-engine/
  Complete output (6 lines):
  running bdist_wheel
  running build
  Building C++ extensions
  ../make-share.sh: 21: cmake: not found
  make: *** No targets specified and no makefile found.  Stop.
  error: [Errno 2] No such file or directory: '/tmp/pip-install-fs9zu9a_/keystone-engine/src/build/llvm/lib64/libkeystone.so'
  ----------------------------------------
  ERROR: Failed building wheel for keystone-engine
  Running setup.py clean for keystone-engine
Failed to build unicorn keystone-engine
Installing collected packages: unicorn, keystone-engine, qiling
  Attempting uninstall: unicorn
    Found existing installation: unicorn 1.0.3
    Uninstalling unicorn-1.0.3:
      Successfully uninstalled unicorn-1.0.3
    Running setup.py install for unicorn ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fs9zu9a_/unicorn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fs9zu9a_/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dq2s5nff/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ubuntu/.local/include/python3.8/unicorn
         cwd: /tmp/pip-install-fs9zu9a_/unicorn/
    Complete output (4 lines):
    running install
    running build
    Building C extensions
    error: [Errno 2] No such file or directory: '/tmp/pip-install-fs9zu9a_/unicorn/../../include/unicorn'
    ----------------------------------------
  Rolling back uninstall of unicorn
  Moving to /home/ubuntu/.local/lib/python3.8/site-packages/unicorn-1.0.3.dist-info/
   from /home/ubuntu/.local/lib/python3.8/site-packages/~nicorn-1.0.3.dist-info
  Moving to /home/ubuntu/.local/lib/python3.8/site-packages/unicorn/
   from /home/ubuntu/.local/lib/python3.8/site-packages/~nicorn
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fs9zu9a_/unicorn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fs9zu9a_/unicorn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-dq2s5nff/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/ubuntu/.local/include/python3.8/unicorn Check the logs for full command output.


―
