### ISSUE TITLE
pe.py set_cmdline is incorrect

### ISSUE THREAD

**Issue by learn-more** [qilingframework/qiling#640]
- The allocation on the heap is done for a char if the target is 32 bit, and as wchar if the target is 64 bit.
- For every exported symbol for every dll loaded there is an allocation done on the os.heap.

**Comment by xwings** [comment]
Once i have time i will take a look, or we need someone to take over the windows part :)

**Comment by wolfcod** [comment]
The cmdline is an attribute available in PEB.ProcessParameters structure, that is missing.
When the program is loaded, this structure must be initialized and GetCommandLineA/GetCommandLineW return a pointer to cmdline itself. DLLs's don't need a pointer to cmdline, because is not required into DllMain, they can retrieve cmdline only through api. It's an argument required by WinMain.

**Comment by learn-more** [comment]
> The cmdline is an attribute available in PEB.ProcessParameters structure, that is missing.
> When the program is loaded, this structure must be initialized and GetCommandLineA/GetCommandLineW return a pointer to cmdline itself. DLLs's don't need a pointer to cmdline, because is not required into DllMain, they can retrieve cmdline only through api. It's an argument required by WinMain.

That is not wrong, but also completely unrelated to this.

**Comment by learn-more** [comment]
Fixed, thanks.
