### ISSUE TITLE
execute example script error：NameError: name 'UC_X86_REG_FS_BASE' is not defined

### ISSUE THREAD

**Issue by 23R3F** [qilingframework/qiling#770]
~/qiling/examples$ python3 netgear_6220_mips32el_linux.py
Traceback (most recent call last):
  File "netgear_6220_mips32el_linux.py", line 21, in <module>
    from qiling.os.posix import syscall
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/posix/syscall/__init__.py", line 5, in <module>
    from .fcntl import *
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/posix/syscall/fcntl.py", line 8, in <module>
    from qiling.os.linux.thread import *
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/linux/thread.py", line 14, in <module>
    from qiling.arch.x86_const import *
  File "/home/zeref/.local/lib/python3.6/site-packages/qiling/arch/x86_const.py", line 110, in <module>
    "fsbase" : UC_X86_REG_FS_BASE,
NameError: name 'UC_X86_REG_FS_BASE' is not defined

it seems that qiling in this version do not import unicorn？？？？because i find the UC_X86_REG_FS_BASE is defined in unicorn/bindings/python/unicorn/x86_const.py

my env info ：
~/qiling/examples$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

~/qiling/examples$ pip3 show qiling
Name: qiling
Version: 1.2.4.dev0
Summary: Qiling is an advanced binary emulation framework that cross-platform-architecture
Home-page: http://qiling.io
Author: None
Author-email: None
License: GPLv2
Location: /home/zeref/.local/lib/python3.6/site-packages
Requires: keystone-engine, pefile, gevent, python-registry, unicorn, capstone, pyelftools
Required-by:

~/qiling/examples$ pip3 show unicorn
Name: unicorn
Version: 1.0.2rc3
Summary: Unicorn CPU emulator engine
Home-page: http://www.unicorn-engine.org
Author: Nguyen Anh Quynh
Author-email: aquynh@gmail.com
License: UNKNOWN
Location: /home/zeref/.local/lib/python3.6/site-packages
Requires: 
Required-by: qiling, pwntools, angr

**Comment by wtdcode** [comment]
Could you try to update your unicorn version?

________________________________
From: 23R3F ***@***.***>
Sent: Tuesday, April 13, 2021 8:32:57 AM
To: qilingframework/qiling ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [qilingframework/qiling] execute example script error：NameError: name 'UC_X86_REG_FS_BASE' is not defined (#770)


~/qiling/examples$ python3 netgear_6220_mips32el_linux.py
Traceback (most recent call last):
File "netgear_6220_mips32el_linux.py", line 21, in
from qiling.os.posix import syscall
File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/posix/syscall/init.py", line 5, in
from .fcntl import *
File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/posix/syscall/fcntl.py", line 8, in
from qiling.os.linux.thread import *
File "/home/zeref/.local/lib/python3.6/site-packages/qiling/os/linux/thread.py", line 14, in
from qiling.arch.x86_const import *
File "/home/zeref/.local/lib/python3.6/site-packages/qiling/arch/x86_const.py", line 110, in
"fsbase" : UC_X86_REG_FS_BASE,
NameError: name 'UC_X86_REG_FS_BASE' is not defined

it seems that qiling in this version do not import unicorn？？？？because i find the UC_X86_REG_FS_BASE is defined in unicorn/bindings/python/unicorn/x86_const.py

my env info ：
~/qiling/examples$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

~/qiling/examples$ pip3 show qiling
Name: qiling
Version: 1.2.4.dev0
Summary: Qiling is an advanced binary emulation framework that cross-platform-architecture
Home-page: http://qiling.io
Author: None
Author-email: None
License: GPLv2
Location: /home/zeref/.local/lib/python3.6/site-packages
Requires: keystone-engine, pefile, gevent, python-registry, unicorn, capstone, pyelftools
Required-by:

~/qiling/examples$ pip3 show unicorn
Name: unicorn
Version: 1.0.2rc3
Summary: Unicorn CPU emulator engine
Home-page: http://www.unicorn-engine.org
Author: Nguyen Anh Quynh
Author-email: ***@***.******@***.***>
License: UNKNOWN
Location: /home/zeref/.local/lib/python3.6/site-packages
Requires:
Required-by: qiling, pwntools, angr

―

**Comment by 23R3F** [comment]
thx，i find my pwntools require the unicorn-1.0.2rc3, remove the pwntools and reinstall unicorn will solve the problem
