### ISSUE TITLE
Qltool Hangs/Runs Infinitely on Certain Files

### ISSUE THREAD

**Issue by djmccarthy12** [qilingframework/qiling#791]
I'm using Qltool to emulate a number of binaries, most of which work fine, but on a particular binary (rstats), it seems to run forever, and the `--timeout` argument does not appear to do anything, nor does ctrl-c (actually ctrl-c LOOKS like it works, it brings me back to my prompt, but then randomly output from Qltool will show up again...). I actually either have to close the terminal window or run `kill -9 <PID>` to kill the process.

Unfortunately this is causing some issues as my program which calls qltool hangs on the command execution (even with a timeout implemented outside of qltool itself in golang). Any idea why this would be happening?

The exact syntax of the qltool execution is as follows:

`qltool run -f rstats --rootfs ../ --args -v --timeout 1000000`

**Comment by elicn** [comment]
Hey there,
Please note that all the arguments specified after `--args` are considered as the emulated program arguments, and not counted as `qltool` arguments. Can you try re-run this but this time without the `--args` token? (note that the `-v` needs a verbosity level to be specified)

`qltool run -f rstats --rootfs ../ -v default --timeout 1000000`

**Comment by djmccarthy12** [comment]
Ah, my apologies, however I have ran it as you described and still experience the same issue, here is the last ~20 lines of the output, if it is at all useful. 

`[=]     unlink(pathname = 0x4045bc)
[=]     open(filename = 0x77502b48, flags = 0x81, mode = 0x0)
[=]     open(filename = 0x774c2c40, flags = 0x2, mode = 0x0)
[=]     write(fd = 0x2, buf = 0x774c2c40, count = 0xa)
/dev/nvram[=]   write(fd = 0x2, buf = 0x7758fc34, count = 0x2)
: [=]   write(fd = 0x2, buf = 0x7ff3b5e0, count = 0x19)
No such file or directory[=]    write(fd = 0x2, buf = 0x7758fc3e, count = 0x1)

[=]     sysinfo(info = 0x7ff3c7e8)
[=]     time()
[=]     open(filename = 0x774c2c40, flags = 0x2, mode = 0x0)
[=]     write(fd = 0x2, buf = 0x774c2c40, count = 0xa)
/dev/nvram[=]   write(fd = 0x2, buf = 0x7758fc34, count = 0x2)
: [=]   write(fd = 0x2, buf = 0x7ff3c588, count = 0x19)
No such file or directory[=]    write(fd = 0x2, buf = 0x7758fc3e, count = 0x1)

[=]     brk(input = 0x0)
[=]     brk(input = 0x532000)
[=]     open(filename = 0x40445c, flags = 0x0, mode = 0x0)
[=]     rt_sigprocmask(sigprocmask_how = 0x1, sigprocmask_nset = 0x7ff3c688, sigprocmask_oset = 0x7ff3c708, sigprocmask_sigsetsize = 0x10)
[=]     rt_sigaction(sigaction_signum = 0x12, sigaction_act = 0x0, sigaction_oldact = 0x7ff3c638)
[=]     rt_sigprocmask(sigprocmask_how = 0x3, sigprocmask_nset = 0x7ff3c708, sigprocmask_oset = 0x0, sigprocmask_sigsetsize = 0x10)
[=]     nanosleep(req = 0x7ff3c680, rem = 0x7ff3c680)`

And then that same pattern is repeated indefinitely until I kill it.

**Comment by elicn** [comment]
It looks like the program you are running tries to repeatedly access `/dev/nvram` without success; still I would expect it to halt when the timeout expires. I tested the `timeout` functionality to make sure it works in the right scale, and it does..

My next suggestions would be:

1. Try giving the executable more time to initialize and run by increasing the timeout to 10s instead of just 1s
2. If possible, zip the executable along with its rootfs directory and attach it here so I would be able to take a closer look

**Comment by djmccarthy12** [comment]
Thanks very much for looking into this. Yeah, I have tried 10 or more seconds as well with the same results. The files were too big to attach (35MB) so I uploaded to Google Drive as a public link here - 

https://drive.google.com/file/d/1qhfrmM2P9pUaCVN_nA5QIW5_gHCJVABV/view?usp=sharing

Let me know if you have any issues accessing it. Link should be good for 24 hours, happy to extend it if needed as well.

The file is from an extracted firmware image, you'll find the rstats binary in /bin.

Also, if it matters at all I am running this on a Debian system running on WSL2. Thanks again!

**Comment by elicn** [comment]
OK, mystery unfolded.

It looks like the program you emulates forks a few times, so probably the parent gets killed by timeout while the children processes are still alive (and trying access `/dev/nvram` ...). I am no expert in multithreaded emulation - perhaps @xwings can comment on that.

The repeated messages you get come from the children processes which keep trying to access `/dev/nvram`. I guess `ql.add_fs_mapper` can help you with this.

Besides that, it looks like the program tries to `execve` another program and fails due to wrong ELF magic number. It turns out that `execve` gets a shell script to execute: `./bin/sh`, a feature Qiling doesn't support. Luckily, the whole script is just a single call to `busybox`, so there is an easy way to work around it: replace `bin/sh` with a symbolic link to `bin/busybox`, as follows:

```bash
cd bin
mv sh sh.bak
ln -s busybox sh
cd -
```

**Comment by djmccarthy12** [comment]
Makes a lot of sense, figured there was something going on with child processes since it looked like killing the initial process was working, but was still seeing output

Really appreciate you working through this one. I have to figure out how to identify when this issue comes up and solve it programmatically from my golang app, but that's obviously outside of the scope on your guys' end. This has been super helpful. Thanks a lot!
